### list differential
GET http://localhost:8080/differential

### get developer
GET http://localhost:8080/differential/35a06a26-e0d3-4b65-90fa-87766e04b424

### create developer
POST http://localhost:8080/differential
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "Palestrante",
    "description": "Falo um pouco"
}

### update developer
PATCH http://localhost:8080/differential/MO15NfMGGaXQaFC1SGP5m
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "Trovador"
}

### delete developer
DELETE http://localhost:8080/differential/35a06a26-e0d3-4b65-90fa-87766e04b424
x-api-key: {{$dotenv.API_KEY}}
