### list project
GET http://localhost:8080/project

### get developer
GET http://localhost:8080/project/056ffa52-7bbd-424d-a2c5-3f126045bf06

### create developer
POST http://localhost:8080/project
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "CRUD Dinossauros",
    "description": "Criar, buscar, editar e remover os dino.",
    "repository": "https://teste.com.br",
    "demo": "https://teste.com.br"
}

### update developer
PATCH http://localhost:8080/project/056ffa52-7bbd-424d-a2c5-3f126045bf06
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "Crud Dinossauros"
}

### delete developer
DELETE http://localhost:8080/project/056ffa52-7bbd-424d-a2c5-3f126045bf06
x-api-key: {{$dotenv.API_KEY}}
