### list project
GET http://localhost:8080/project

### get developer
GET http://localhost:8080/project/zezTDrrTC5Xrx7xLOgRJK

### create developer
POST http://localhost:8080/project
Content-Type: application/json

{
    "title": "CRUD Dinossauros",
    "description": "Criar, buscar, editar e remover os dino.",
    "repository": "https://teste.com.br",
    "demo": "https://teste.com.br"
}

### update developer
PATCH http://localhost:8080/project/zezTDrrTC5Xrx7xLOgRJK
Content-Type: application/json

{
    "title": "Crud Dinossauros"
}

### delete developer
DELETE http://localhost:8080/project/zezTDrrTC5Xrx7xLOgRJK