### list project
GET http://localhost:8080/project

### get developer
GET http://localhost:8080/project/hWRArPwzjFWgooLFiZcUH

### create developer
POST http://localhost:8080/project
Content-Type: application/json

{
    "title": "CRUD Dinossauros",
    "description": "Criar, buscar, editar e remover os dino.",
    "repository": "https://teste.com.br",
    "demo": "https://teste.com.br"
}

### update developer
PATCH http://localhost:8080/project/IG2gQ9Tx7P_aS07kUrt9q
Content-Type: application/json

{
    "title": "Crud Dinossauros"
}

### delete developer
DELETE http://localhost:8080/project/IG2gQ9Tx7P_aS07kUrt9q