### list work
GET http://localhost:8080/work

### get developer
GET http://localhost:8080/work/953945ff-5918-4cbb-b0a7-f7302c152749

### create developer
POST http://localhost:8080/work
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "Faccat",
    "description": "Um evento muito bonito que eu gostei",
    "image": "https://teste.com.br"
}

### update developer
PATCH http://localhost:8080/work/953945ff-5918-4cbb-b0a7-f7302c152749
Content-Type: application/json
x-api-key: {{$dotenv.API_KEY}}

{
    "title": "Fac CLJ"
}

### delete developer
DELETE http://localhost:8080/work/953945ff-5918-4cbb-b0a7-f7302c152749
x-api-key: {{$dotenv.API_KEY}}
